[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["ecommercegraphql"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "ecommercegraphql"
  org = "ayeshadissanayaka"
  version = "1.0.1"

